import 'angular-ui-router';
import "angular-ui-router-styles/ui-router-styles";
import "angular-jwt/";
import "ng-idle/";
import "angular-ui-bootstrap/";
import "angular-animate/";
//import "angular-drag-drop/"

//Import our app functionaity
import "./modules/modules";
import "./modules/templates/templates.module";
import "./modules/(main-app)/";
import "./modules/[directives]/";
import "./modules/[services]/";
import "./modules/home/";
import "./modules/cart/";
import "./modules/community/";
import "./modules/downtown/";
import "./modules/help/";
import "./modules/search/";
import "./modules/setting/";
import "./modules/signin/";
import "./modules/auth/";
import "./modules/signout/";
import "./modules/user/";
import "./modules/shop/";
import "./modules/item/";
//import "./modules/email/";
//import "./modules/calendar/";
import "./modules/chat/";
import "./modules/timeline/";
import "./modules/mail/";
import "./modules/contacts/";
import "./modules/notes/";
import "./modules/calendar/";
